config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users, only: [:new, :show, :create]
  resources :rewards
  resources :points, only: [:edit]

  resources :user_rewards, only: [:create, :update]

  namespace :admin do
    resources :rewards, only: [:index, :new, :edit]
    resources :points, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show] do
      resources :points, only: [:create, :destroy]
    end
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  validates_presence_of :user_id, :status
  belongs_to :user
  enum status: [:active, :redeemed]
end

app/models/reward.rb
class Reward < ApplicationRecord
  validates_presence_of :title, :value, :description
  has_many :user_rewards, dependent: :destroy
  has_many :users, through: :user_rewards
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :points, dependent: :destroy
  has_many :user_rewards, dependent: :destroy
  has_many :rewards, through: :user_rewards
  has_secure_password
  enum role: %w(default admin)

  def total_points
    points.count
  end

  def subtract_points(value)
    value.times do
      points.last.destroy
    end
  end
end

app/models/user_reward.rb
class UserReward < ApplicationRecord
  belongs_to :user
  belongs_to :reward
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/points_controller.rb
class Admin::PointsController < Admin::BaseController
  def new
    @point = Point.new
  end

  def create
    @user = User.find(params[:user_id])
    Point.create!(user_id: @user.id, status: 0)
    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    if @user.points.count >= 1
      @point = @user.points.last.destroy
    end
    redirect_to admin_user_path(@user)
  end
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController

  def index
    @rewards = Reward.all
  end

  def new
    @reward = Reward.new
  end

  def edit
    @reward = Reward.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def current_default?
    current_user && current_user.default?
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @rewards = Reward.all
  end

  def update
    @reward = Reward.find(params[:id])
    @reward.update(reward_params)
    flash.notice = "#{@reward.title} was updated!"
    redirect_to admin_rewards_path
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy

    flash[:success] = "#{@reward.title} was deleted."
    redirect_to admin_rewards_path
  end

  def create
    reward = Reward.new(reward_params)
    if reward.save
      flash.notice = "#{reward.title} was created!"
      redirect_to admin_rewards_path
    else
      flash.notice = 'Missing required information!'
      redirect_to new_admin_reward_path
    end
  end

  def edit

  end

  private
    def reward_params
      params.require(:reward).permit(:title, :description, :image, :value)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      flash[:notice] = "You are now logged in!"
      session[:user_id] = user.id
      if user.role == 'admin'
        redirect_to admin_users_path
      else
        redirect_to user_path(user)
      end
    else
      flash[:notice] = "Try again!"
      render :new
    end
  end

  def destroy
    flash[:notice] = "You have logged out!"
    session.clear
    redirect_to root_path
  end
end

app/controllers/user_rewards_controller.rb
class UserRewardsController < ApplicationController
  def create
    user_reward = UserReward.new(user_id: params[:user_id], reward_id: params[:reward_id])
    reward_value = Reward.find(params[:reward_id]).value

    if current_user.total_points >= reward_value
      user_reward.save
      current_user.subtract_points(reward_value)
      redirect_to user_path(current_user), notice: "You have redeemed this reward!"
    else
      flash[:notice] = "Sorry, you don't have enough available points!"
      redirect_to rewards_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if current_admin?
        redirect_to admin_users_path
      else
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      end
    else
      flash[:notice] = 'Try again!'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @correct_user = current_user == @user
    @users = User.all
  end

  private

    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rewards/_form.html.erb
<div class="form">
  <%= form_for @reward do |f| %>
    <div class="form-group">
      <%= f.label :title %>:
      <%= f.text_field :title %>
    </div>

    <div class="form-group">
      <%= f.label :value %>:
      <%= f.number_field :value %>
    </div>

    <div class="form-group">
      <%= f.label :description %>:
      <%= f.text_area :description %>
    </div>

    <div class="button">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/admin/rewards/edit.html.erb
<div class="page-header">
  Update Reward Here!
</div>

<%= render partial: "partial/flash" %>

<%= render partial: "form" %>

app/views/admin/rewards/index.html.erb
<div class="page-header">
  Rewards
</div>

<%= render partial: "partial/flash" %>

<div class="button">
  <%= link_to "Add a Reward", new_admin_reward_path %>
</div>

<div class="flex-box">
  <% @rewards.each do |reward| %>
    <div class="box">
      <strong><%= reward.title %></strong>
      <strong><h4><%= reward.description %></h4></strong>
      <strong><h4><%= reward.value %> Points</h4></strong>
      <% if current_user %>
        <div class="button">
          <%= link_to "Update Reward", edit_admin_reward_path(reward), title: reward.title %>
          <%= link_to "Delete Reward", reward_path(reward), title: reward.description, method: "delete", data: {confirm: "Are you sure you want to delete #{reward.title}?"} %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/rewards/new.html.erb
<div class="page-header">
  Add A Reward Here!
</div>

<%= render partial: "partial/flash" %>

<%= render partial: "form" %>

app/views/admin/users/index.html.erb
<div class="page-header">
  All Users
</div>

<%= render partial: "partial/flash" %>

<div class="new">
  <%= link_to "Create a New User", new_user_path %>
</div>

<div class="info">
  <% @users.each do |user| %>
  <div>
    <%= link_to user.username, admin_user_path(user) %>
  </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="page-header">
  <%= @user.username %>'s Points
</div>

<%= render partial: "partial/flash" %>

<div class="info">
  <strong>Total Points:</strong>  <%= @user.points.count %><br>
</div>

<div class="button">
  <%= link_to "Assign Point to #{@user.username}", admin_user_points_path(@user), method: :post %>
</div>
<div class="button">
  <%= link_to "Delete Point from #{@user.username}", admin_user_point_path(@user), method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointsBox</title>
    <link href='https://fonts.googleapis.com/css?family=Gloria Hallelujah' rel='stylesheet'>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "main.css" %>
    <%= csrf_meta_tags %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "partial/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/partial/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>

app/views/partial/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="d-inline-block align-top" alt="PointsBox Logo">
        PointsBox
      </a>
    </div>
    <ul class="nav navbar-nav">
      <% if current_user && current_user.admin? %>
        <li class="<%= "active" if params[:controller] == "rewards" %>"><%= link_to "Rewards", admin_rewards_path %></li>
        <li class="<%= "active" if params[:controller] == "user" %>"><%= link_to "Users", admin_users_path %></li>
        <li class="<%= "active" if params[:controller] == "sessions" %>"><%= link_to "Log Out", logout_path, method: "delete" %></li>
      <% elsif current_user && current_user.default? %>
        <li class="<%= "active" if params[:controller] == "rewards" %>"><%= link_to "Rewards", rewards_path %></li>
        <li class="<%= "active" if params[:controller] == "user" %>"><%= link_to "My Profile", user_path(current_user) %></li>
        <li class="<%= "active" if params[:controller] == "sessions" %>"><%= link_to "Log Out", logout_path, method: "delete" %></li>
      <% else %>
        <li class="<%= "active" if params[:controller] == "rewards" %>"><%= link_to "Rewards", rewards_path %></li>
        <li class="<%= "active" if params[:controller] == "sessions" %>"><%= link_to "Log In", login_path %></li>
        <li class="<%= "active" if params[:controller] == "users" %>"><%= link_to 'Register', new_user_path %></li>
      <% end %>
  </div>
</nav>

app/views/rewards/index.html.erb
<div class="page-header">
  Rewards
</div>

<%= render partial: "partial/flash" %>

<div class="flex-box">
  <% @rewards.each do |reward| %>
    <div class="box">
      <strong><%= reward.title %></strong>
      <strong><h4><%= reward.description %><h4></strong>
      <strong><h4><%= reward.value %> Points</h4></strong>
      <% if current_user %>
      <div class="button">
        <h3><%= link_to "Redeem #{reward.title}", user_rewards_path(user_id: current_user.id, reward_id: reward.id), method: :post %></h3>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="page-header">
  Register Here!
</div>

<%= render partial: "partial/flash" %>

<div class="form">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :username %>:
      <%= f.text_field :username %>
    </div>

    <div class="form-group">
      <%= f.label :password %>:
      <%= f.password_field :password %>
    </div>

    <div class="button">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% if @correct_user %>
  <div class="page-header">
    Welcome, <%= current_user.username %>!
  </div>

  <%= render partial: "partial/flash" %>

  <div class="info">
    <div class="box">
      <strong>Total Points:</strong>  <%= @user.total_points %>
    </div>
    <div class="flex-box">
      <strong>Rewards Earned:</strong><br>
      <% current_user.rewards.each do |reward| %>
        <div class="box">
          <strong><%= reward.title %></strong><br>
          <%= reward.description %><br>
          <%= reward.value %> Points<br>
        </div>
      <% end %>
    </div>
  </div><br>
<% else %>
  <%= render file: "/public/404" %>
<% end %>

app/views/welcome/index.html.erb
<%= render partial: "partial/flash" %>

<div class="intro">
  Welcome to PointsBox!
</div>

<div class="logo">
  <img src="/assets/logo.png" alt="PointsBox Logo">
</div>